version: "4"
services:
  postgres:
    container_name: postgres-challenge
    hostname: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge-local